[build]
  command = "cd mycompetence-webapi && npm install && npm run build && cd .. && cd mycompetence-frontend && npm install && npm run publish"
  functions = "mycompetence-webapi/lambda" # Serverless Functions
  publish = "mycompetence-frontend/dist/mycompetence"   # Angular Client

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
