[build]
  command = "cd mycompetence-webapi && npm install && npm run build"
  functions = "mycompetence-webapi/lambda"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
