name: CI

on:
  push:
  workflow_dispatch:

jobs:
  Build-Frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mycompetence-frontend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
           node-version: '12'

      - name: Install
        run: npm install
      
      - name: Build
        run: npm run build
        
      - name: Deploy
        uses: jsmrcaga/action-netlify-deploy@v1.1.0
        if: github.ref == 'refs/heads/production'
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.WEBSITE_TOKEN }}
          NETLIFY_SITE_ID: 7399a8dd-a16d-4ca7-b8ae-e51b17a81194
          NETLIFY_DEPLOY_TO_PROD: true
        
  Build-Backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mycompetence-webapi
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
           node-version: '12'

      - name: Install
        run: |
          echo "export const DATABASE_SECRET = \"PLACEHOLDER\"" > src/environment.ts 
          npm install netlify-cli -g
          npm install
      
      - name: Build
        run: npm run build        
