name: CI

on:
  push:
  workflow_dispatch:

jobs:
  Build-Frontend-Backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
           node-version: '12'

      - name: Install
        run:  |
          npm install netlify-cli -g
          cd ./mycompetence-frontend
          npm install 
          cd ..
          cd ./mycompetence-webapi
          echo "export const DATABASE_SECRET = \"PLACEHOLDER\"" > src/environment.ts 
          npm install
          cd ..
      
      - name: Build
        run: |
          cd ./mycompetence-frontend
          npm run build 
          cd ..
          cd ./mycompetence-webapi
          npm run build 
          cd ..
        
      - name: Deploy
        uses: jsmrcaga/action-netlify-deploy@v1.1.0
      #  if: github.ref == 'refs/heads/production'
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.WEBSITE_TOKEN }}
          NETLIFY_SITE_ID: 7399a8dd-a16d-4ca7-b8ae-e51b17a81194
          NETLIFY_DEPLOY_TO_PROD: true
