name: CI

on:
  push:
  workflow_dispatch:

jobs:
  Build-Frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mycompetence-frontend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
           node-version: '12'

      - name: Install
        run: npm install
      
      - name: Build
        run: npm run build
        
  Build-Backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mycompetence-webapi
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
           node-version: '12'

      - name: Install
        run: |
          echo "export const DATABASE_SECRET = \"PLACEHOLDER"" > src/environment.ts 
          npm install netlify-cli -g
          npm install
      
      - name: Build
        run: npm run build        
